package SwingHibernate;

import javax.swing.*;
import java.util.*;
import entities.*;
import dao.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ToanPhamOk
 */
public class Login extends javax.swing.JFrame {

    private UsersDao udao = new UsersDao();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(530, 289);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        txtPassword.setText("123");
        txtUsername.setText("nhanvien1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 20, 167, 32);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tài Khoản");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 69, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mật Khẩu");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 70, 30);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(120, 70, 225, 29);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(120, 110, 225, 29);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incons/Log out.png"))); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 170, 128, 33);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incons/Login.png"))); // NOI18N
        jButton1.setText("Đăng nhập ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 170, 135, 33);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modern-city-skyline-background_77417-791.jpg"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(625, 355));
        jLabel5.setPreferredSize(new java.awt.Dimension(655, 355));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 530, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String username = txtUsername.getText();
            if (kiemtra1() && kiemtra2()) {
                JOptionPane.showMessageDialog(this, "ĐĂNG NHẬP THÀNH CÔNG");
                Users u = udao.find(username);
                if(u != null){
                    String role = u.getRole();
                    if(role.equals("nv")){
                        FormNV fnv = new FormNV(u);
                        fnv.setVisible(true);
                    }else{
                        FormQL fql = new FormQL();
                        fql.setVisible(true);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed
    public boolean kiemtra1() {
        String username = txtUsername.getText();
        if (username.length() == 0) {
            JOptionPane.showMessageDialog(this, "KHÔNG BỎ TRỐNG USERNAME");
            return false;
        }
        String password = new String(txtPassword.getPassword());
        if (password.length() == 0) {
            JOptionPane.showMessageDialog(this, "KHÔNG BỎ TRỐNG PASSWORD");
            return false;
        }
        return true;
    }

    public boolean kiemtra2() {
        boolean test = false;
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());
        for (Users u : udao.danhsach()) {
            if (String.valueOf(u.getUsername()).equalsIgnoreCase(username) && u.getPassword().equals(password)) {
                return true;
            }
        }
        if (!test) {
            JOptionPane.showMessageDialog(this, "USERNAME HOẶC PASSWORD KHÔNG CHÍNH XÁC");
        }
        return test;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws java.lang.InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
