package entities;
// Generated Oct 13, 2019 1:33:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Cthd generated by hbm2java
 */
public class Cthd  implements java.io.Serializable {


     private int maHd;
     private Khachhang khachhang;
     private Phong phong;
     private Date checkin;
     private Date checkout;
     private String username;

    public Cthd() {
    }

	
    public Cthd(int maHd, Khachhang khachhang, Phong phong) {
        this.maHd = maHd;
        this.khachhang = khachhang;
        this.phong = phong;
    }
    public Cthd(int maHd, Khachhang khachhang, Phong phong, Date checkin, Date checkout, String username) {
       this.maHd = maHd;
       this.khachhang = khachhang;
       this.phong = phong;
       this.checkin = checkin;
       this.checkout = checkout;
       this.username = username;
    }
   
    public int getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(int maHd) {
        this.maHd = maHd;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Phong getPhong() {
        return this.phong;
    }
    
    public void setPhong(Phong phong) {
        this.phong = phong;
    }
    public Date getCheckin() {
        return this.checkin;
    }
    
    public void setCheckin(Date checkin) {
        this.checkin = checkin;
    }
    public Date getCheckout() {
        return this.checkout;
    }
    
    public void setCheckout(Date checkout) {
        this.checkout = checkout;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


