package entities;
// Generated Oct 13, 2019 1:33:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private String cmnd;
     private String hoten;
     private Boolean gtinh;
     private String sdt;
     private Set cthds = new HashSet(0);

    public Khachhang() {
    }

	
    public Khachhang(String cmnd) {
        this.cmnd = cmnd;
    }
    public Khachhang(String cmnd, String hoten, Boolean gtinh, String sdt, Set cthds) {
       this.cmnd = cmnd;
       this.hoten = hoten;
       this.gtinh = gtinh;
       this.sdt = sdt;
       this.cthds = cthds;
    }
   
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public Boolean getGtinh() {
        return this.gtinh;
    }
    
    public void setGtinh(Boolean gtinh) {
        this.gtinh = gtinh;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public Set getCthds() {
        return this.cthds;
    }
    
    public void setCthds(Set cthds) {
        this.cthds = cthds;
    }




}


